// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package deaggregator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{0}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Record struct {
	PartitionKeyIndex    *uint64  `protobuf:"varint,1,req,name=partition_key_index,json=partitionKeyIndex" json:"partition_key_index,omitempty"`
	ExplicitHashKeyIndex *uint64  `protobuf:"varint,2,opt,name=explicit_hash_key_index,json=explicitHashKeyIndex" json:"explicit_hash_key_index,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{1}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetPartitionKeyIndex() uint64 {
	if m != nil && m.PartitionKeyIndex != nil {
		return *m.PartitionKeyIndex
	}
	return 0
}

func (m *Record) GetExplicitHashKeyIndex() uint64 {
	if m != nil && m.ExplicitHashKeyIndex != nil {
		return *m.ExplicitHashKeyIndex
	}
	return 0
}

func (m *Record) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Record) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AggregatedRecord struct {
	PartitionKeyTable    []string  `protobuf:"bytes,1,rep,name=partition_key_table,json=partitionKeyTable" json:"partition_key_table,omitempty"`
	ExplicitHashKeyTable []string  `protobuf:"bytes,2,rep,name=explicit_hash_key_table,json=explicitHashKeyTable" json:"explicit_hash_key_table,omitempty"`
	Records              []*Record `protobuf:"bytes,3,rep,name=records" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AggregatedRecord) Reset()         { *m = AggregatedRecord{} }
func (m *AggregatedRecord) String() string { return proto.CompactTextString(m) }
func (*AggregatedRecord) ProtoMessage()    {}
func (*AggregatedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{2}
}
func (m *AggregatedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedRecord.Unmarshal(m, b)
}
func (m *AggregatedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedRecord.Marshal(b, m, deterministic)
}
func (dst *AggregatedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedRecord.Merge(dst, src)
}
func (m *AggregatedRecord) XXX_Size() int {
	return xxx_messageInfo_AggregatedRecord.Size(m)
}
func (m *AggregatedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedRecord proto.InternalMessageInfo

func (m *AggregatedRecord) GetPartitionKeyTable() []string {
	if m != nil {
		return m.PartitionKeyTable
	}
	return nil
}

func (m *AggregatedRecord) GetExplicitHashKeyTable() []string {
	if m != nil {
		return m.ExplicitHashKeyTable
	}
	return nil
}

func (m *AggregatedRecord) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Message struct {
	Id       *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	SourceId *uint64 `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	// Types that are valid to be assigned to ActualMessage:
	//	*Message_PutRecord
	//	*Message_Flush
	//	*Message_PutRecordResult
	//	*Message_Configuration
	//	*Message_MetricsRequest
	//	*Message_MetricsResponse
	//	*Message_SetCredentials
	ActualMessage        isMessage_ActualMessage `protobuf_oneof:"actual_message"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message) GetSourceId() uint64 {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return 0
}

type isMessage_ActualMessage interface {
	isMessage_ActualMessage()
}

type Message_PutRecord struct {
	PutRecord *PutRecord `protobuf:"bytes,3,opt,name=put_record,json=putRecord,oneof"`
}

type Message_Flush struct {
	Flush *Flush `protobuf:"bytes,4,opt,name=flush,oneof"`
}

type Message_PutRecordResult struct {
	PutRecordResult *PutRecordResult `protobuf:"bytes,5,opt,name=put_record_result,json=putRecordResult,oneof"`
}

type Message_Configuration struct {
	Configuration *Configuration `protobuf:"bytes,6,opt,name=configuration,oneof"`
}

type Message_MetricsRequest struct {
	MetricsRequest *MetricsRequest `protobuf:"bytes,7,opt,name=metrics_request,json=metricsRequest,oneof"`
}

type Message_MetricsResponse struct {
	MetricsResponse *MetricsResponse `protobuf:"bytes,8,opt,name=metrics_response,json=metricsResponse,oneof"`
}

type Message_SetCredentials struct {
	SetCredentials *SetCredentials `protobuf:"bytes,9,opt,name=set_credentials,json=setCredentials,oneof"`
}

func (*Message_PutRecord) isMessage_ActualMessage() {}

func (*Message_Flush) isMessage_ActualMessage() {}

func (*Message_PutRecordResult) isMessage_ActualMessage() {}

func (*Message_Configuration) isMessage_ActualMessage() {}

func (*Message_MetricsRequest) isMessage_ActualMessage() {}

func (*Message_MetricsResponse) isMessage_ActualMessage() {}

func (*Message_SetCredentials) isMessage_ActualMessage() {}

func (m *Message) GetActualMessage() isMessage_ActualMessage {
	if m != nil {
		return m.ActualMessage
	}
	return nil
}

func (m *Message) GetPutRecord() *PutRecord {
	if x, ok := m.GetActualMessage().(*Message_PutRecord); ok {
		return x.PutRecord
	}
	return nil
}

func (m *Message) GetFlush() *Flush {
	if x, ok := m.GetActualMessage().(*Message_Flush); ok {
		return x.Flush
	}
	return nil
}

func (m *Message) GetPutRecordResult() *PutRecordResult {
	if x, ok := m.GetActualMessage().(*Message_PutRecordResult); ok {
		return x.PutRecordResult
	}
	return nil
}

func (m *Message) GetConfiguration() *Configuration {
	if x, ok := m.GetActualMessage().(*Message_Configuration); ok {
		return x.Configuration
	}
	return nil
}

func (m *Message) GetMetricsRequest() *MetricsRequest {
	if x, ok := m.GetActualMessage().(*Message_MetricsRequest); ok {
		return x.MetricsRequest
	}
	return nil
}

func (m *Message) GetMetricsResponse() *MetricsResponse {
	if x, ok := m.GetActualMessage().(*Message_MetricsResponse); ok {
		return x.MetricsResponse
	}
	return nil
}

func (m *Message) GetSetCredentials() *SetCredentials {
	if x, ok := m.GetActualMessage().(*Message_SetCredentials); ok {
		return x.SetCredentials
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_PutRecord)(nil),
		(*Message_Flush)(nil),
		(*Message_PutRecordResult)(nil),
		(*Message_Configuration)(nil),
		(*Message_MetricsRequest)(nil),
		(*Message_MetricsResponse)(nil),
		(*Message_SetCredentials)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// actual_message
	switch x := m.ActualMessage.(type) {
	case *Message_PutRecord:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutRecord); err != nil {
			return err
		}
	case *Message_Flush:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Flush); err != nil {
			return err
		}
	case *Message_PutRecordResult:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutRecordResult); err != nil {
			return err
		}
	case *Message_Configuration:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Configuration); err != nil {
			return err
		}
	case *Message_MetricsRequest:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetricsRequest); err != nil {
			return err
		}
	case *Message_MetricsResponse:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MetricsResponse); err != nil {
			return err
		}
	case *Message_SetCredentials:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetCredentials); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.ActualMessage has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 3: // actual_message.put_record
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRecord)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_PutRecord{msg}
		return true, err
	case 4: // actual_message.flush
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Flush)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_Flush{msg}
		return true, err
	case 5: // actual_message.put_record_result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRecordResult)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_PutRecordResult{msg}
		return true, err
	case 6: // actual_message.configuration
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Configuration)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_Configuration{msg}
		return true, err
	case 7: // actual_message.metrics_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MetricsRequest)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_MetricsRequest{msg}
		return true, err
	case 8: // actual_message.metrics_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MetricsResponse)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_MetricsResponse{msg}
		return true, err
	case 9: // actual_message.set_credentials
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetCredentials)
		err := b.DecodeMessage(msg)
		m.ActualMessage = &Message_SetCredentials{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// actual_message
	switch x := m.ActualMessage.(type) {
	case *Message_PutRecord:
		s := proto.Size(x.PutRecord)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Flush:
		s := proto.Size(x.Flush)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutRecordResult:
		s := proto.Size(x.PutRecordResult)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Configuration:
		s := proto.Size(x.Configuration)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MetricsRequest:
		s := proto.Size(x.MetricsRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_MetricsResponse:
		s := proto.Size(x.MetricsResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_SetCredentials:
		s := proto.Size(x.SetCredentials)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PutRecord struct {
	StreamName           *string  `protobuf:"bytes,1,req,name=stream_name,json=streamName" json:"stream_name,omitempty"`
	PartitionKey         *string  `protobuf:"bytes,2,req,name=partition_key,json=partitionKey" json:"partition_key,omitempty"`
	ExplicitHashKey      *string  `protobuf:"bytes,3,opt,name=explicit_hash_key,json=explicitHashKey" json:"explicit_hash_key,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRecord) Reset()         { *m = PutRecord{} }
func (m *PutRecord) String() string { return proto.CompactTextString(m) }
func (*PutRecord) ProtoMessage()    {}
func (*PutRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{4}
}
func (m *PutRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecord.Unmarshal(m, b)
}
func (m *PutRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecord.Marshal(b, m, deterministic)
}
func (dst *PutRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecord.Merge(dst, src)
}
func (m *PutRecord) XXX_Size() int {
	return xxx_messageInfo_PutRecord.Size(m)
}
func (m *PutRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecord proto.InternalMessageInfo

func (m *PutRecord) GetStreamName() string {
	if m != nil && m.StreamName != nil {
		return *m.StreamName
	}
	return ""
}

func (m *PutRecord) GetPartitionKey() string {
	if m != nil && m.PartitionKey != nil {
		return *m.PartitionKey
	}
	return ""
}

func (m *PutRecord) GetExplicitHashKey() string {
	if m != nil && m.ExplicitHashKey != nil {
		return *m.ExplicitHashKey
	}
	return ""
}

func (m *PutRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Flush struct {
	StreamName           *string  `protobuf:"bytes,1,opt,name=stream_name,json=streamName" json:"stream_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flush) Reset()         { *m = Flush{} }
func (m *Flush) String() string { return proto.CompactTextString(m) }
func (*Flush) ProtoMessage()    {}
func (*Flush) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{5}
}
func (m *Flush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flush.Unmarshal(m, b)
}
func (m *Flush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flush.Marshal(b, m, deterministic)
}
func (dst *Flush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flush.Merge(dst, src)
}
func (m *Flush) XXX_Size() int {
	return xxx_messageInfo_Flush.Size(m)
}
func (m *Flush) XXX_DiscardUnknown() {
	xxx_messageInfo_Flush.DiscardUnknown(m)
}

var xxx_messageInfo_Flush proto.InternalMessageInfo

func (m *Flush) GetStreamName() string {
	if m != nil && m.StreamName != nil {
		return *m.StreamName
	}
	return ""
}

type Attempt struct {
	Delay                *uint32  `protobuf:"varint,1,req,name=delay" json:"delay,omitempty"`
	Duration             *uint32  `protobuf:"varint,2,req,name=duration" json:"duration,omitempty"`
	Success              *bool    `protobuf:"varint,3,req,name=success" json:"success,omitempty"`
	ErrorCode            *string  `protobuf:"bytes,4,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage         *string  `protobuf:"bytes,5,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attempt) Reset()         { *m = Attempt{} }
func (m *Attempt) String() string { return proto.CompactTextString(m) }
func (*Attempt) ProtoMessage()    {}
func (*Attempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{6}
}
func (m *Attempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attempt.Unmarshal(m, b)
}
func (m *Attempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attempt.Marshal(b, m, deterministic)
}
func (dst *Attempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attempt.Merge(dst, src)
}
func (m *Attempt) XXX_Size() int {
	return xxx_messageInfo_Attempt.Size(m)
}
func (m *Attempt) XXX_DiscardUnknown() {
	xxx_messageInfo_Attempt.DiscardUnknown(m)
}

var xxx_messageInfo_Attempt proto.InternalMessageInfo

func (m *Attempt) GetDelay() uint32 {
	if m != nil && m.Delay != nil {
		return *m.Delay
	}
	return 0
}

func (m *Attempt) GetDuration() uint32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *Attempt) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Attempt) GetErrorCode() string {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ""
}

func (m *Attempt) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type PutRecordResult struct {
	Attempts             []*Attempt `protobuf:"bytes,1,rep,name=attempts" json:"attempts,omitempty"`
	Success              *bool      `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	ShardId              *string    `protobuf:"bytes,3,opt,name=shard_id,json=shardId" json:"shard_id,omitempty"`
	SequenceNumber       *string    `protobuf:"bytes,4,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutRecordResult) Reset()         { *m = PutRecordResult{} }
func (m *PutRecordResult) String() string { return proto.CompactTextString(m) }
func (*PutRecordResult) ProtoMessage()    {}
func (*PutRecordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{7}
}
func (m *PutRecordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecordResult.Unmarshal(m, b)
}
func (m *PutRecordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecordResult.Marshal(b, m, deterministic)
}
func (dst *PutRecordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecordResult.Merge(dst, src)
}
func (m *PutRecordResult) XXX_Size() int {
	return xxx_messageInfo_PutRecordResult.Size(m)
}
func (m *PutRecordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecordResult.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecordResult proto.InternalMessageInfo

func (m *PutRecordResult) GetAttempts() []*Attempt {
	if m != nil {
		return m.Attempts
	}
	return nil
}

func (m *PutRecordResult) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *PutRecordResult) GetShardId() string {
	if m != nil && m.ShardId != nil {
		return *m.ShardId
	}
	return ""
}

func (m *PutRecordResult) GetSequenceNumber() string {
	if m != nil && m.SequenceNumber != nil {
		return *m.SequenceNumber
	}
	return ""
}

type Credentials struct {
	Akid                 *string  `protobuf:"bytes,1,req,name=akid" json:"akid,omitempty"`
	SecretKey            *string  `protobuf:"bytes,2,req,name=secret_key,json=secretKey" json:"secret_key,omitempty"`
	Token                *string  `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{8}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetAkid() string {
	if m != nil && m.Akid != nil {
		return *m.Akid
	}
	return ""
}

func (m *Credentials) GetSecretKey() string {
	if m != nil && m.SecretKey != nil {
		return *m.SecretKey
	}
	return ""
}

func (m *Credentials) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type SetCredentials struct {
	ForMetrics           *bool        `protobuf:"varint,1,opt,name=for_metrics,json=forMetrics" json:"for_metrics,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,2,req,name=credentials" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetCredentials) Reset()         { *m = SetCredentials{} }
func (m *SetCredentials) String() string { return proto.CompactTextString(m) }
func (*SetCredentials) ProtoMessage()    {}
func (*SetCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{9}
}
func (m *SetCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCredentials.Unmarshal(m, b)
}
func (m *SetCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCredentials.Marshal(b, m, deterministic)
}
func (dst *SetCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCredentials.Merge(dst, src)
}
func (m *SetCredentials) XXX_Size() int {
	return xxx_messageInfo_SetCredentials.Size(m)
}
func (m *SetCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_SetCredentials proto.InternalMessageInfo

func (m *SetCredentials) GetForMetrics() bool {
	if m != nil && m.ForMetrics != nil {
		return *m.ForMetrics
	}
	return false
}

func (m *SetCredentials) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Dimension struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dimension) Reset()         { *m = Dimension{} }
func (m *Dimension) String() string { return proto.CompactTextString(m) }
func (*Dimension) ProtoMessage()    {}
func (*Dimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{10}
}
func (m *Dimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dimension.Unmarshal(m, b)
}
func (m *Dimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dimension.Marshal(b, m, deterministic)
}
func (dst *Dimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dimension.Merge(dst, src)
}
func (m *Dimension) XXX_Size() int {
	return xxx_messageInfo_Dimension.Size(m)
}
func (m *Dimension) XXX_DiscardUnknown() {
	xxx_messageInfo_Dimension.DiscardUnknown(m)
}

var xxx_messageInfo_Dimension proto.InternalMessageInfo

func (m *Dimension) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Dimension) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Stats struct {
	Count                *float64 `protobuf:"fixed64,1,req,name=count" json:"count,omitempty"`
	Sum                  *float64 `protobuf:"fixed64,2,req,name=sum" json:"sum,omitempty"`
	Mean                 *float64 `protobuf:"fixed64,3,req,name=mean" json:"mean,omitempty"`
	Min                  *float64 `protobuf:"fixed64,4,req,name=min" json:"min,omitempty"`
	Max                  *float64 `protobuf:"fixed64,5,req,name=max" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{11}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetCount() float64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Stats) GetSum() float64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func (m *Stats) GetMean() float64 {
	if m != nil && m.Mean != nil {
		return *m.Mean
	}
	return 0
}

func (m *Stats) GetMin() float64 {
	if m != nil && m.Min != nil {
		return *m.Min
	}
	return 0
}

func (m *Stats) GetMax() float64 {
	if m != nil && m.Max != nil {
		return *m.Max
	}
	return 0
}

type Metric struct {
	Name                 *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Dimensions           []*Dimension `protobuf:"bytes,2,rep,name=dimensions" json:"dimensions,omitempty"`
	Stats                *Stats       `protobuf:"bytes,3,req,name=stats" json:"stats,omitempty"`
	Seconds              *uint64      `protobuf:"varint,4,req,name=seconds" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{12}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Metric) GetDimensions() []*Dimension {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *Metric) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Metric) GetSeconds() uint64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

type MetricsRequest struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Seconds              *uint64  `protobuf:"varint,2,opt,name=seconds" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsRequest) Reset()         { *m = MetricsRequest{} }
func (m *MetricsRequest) String() string { return proto.CompactTextString(m) }
func (*MetricsRequest) ProtoMessage()    {}
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{13}
}
func (m *MetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsRequest.Unmarshal(m, b)
}
func (m *MetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsRequest.Marshal(b, m, deterministic)
}
func (dst *MetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsRequest.Merge(dst, src)
}
func (m *MetricsRequest) XXX_Size() int {
	return xxx_messageInfo_MetricsRequest.Size(m)
}
func (m *MetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsRequest proto.InternalMessageInfo

func (m *MetricsRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MetricsRequest) GetSeconds() uint64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

type MetricsResponse struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricsResponse) Reset()         { *m = MetricsResponse{} }
func (m *MetricsResponse) String() string { return proto.CompactTextString(m) }
func (*MetricsResponse) ProtoMessage()    {}
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_0c7e4ef6cf0a996e, []int{14}
}
func (m *MetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsResponse.Unmarshal(m, b)
}
func (m *MetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsResponse.Marshal(b, m, deterministic)
}
func (dst *MetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsResponse.Merge(dst, src)
}
func (m *MetricsResponse) XXX_Size() int {
	return xxx_messageInfo_MetricsResponse.Size(m)
}
func (m *MetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsResponse proto.InternalMessageInfo

func (m *MetricsResponse) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*Tag)(nil), "aws.kinesis.protobuf.Tag")
	proto.RegisterType((*Record)(nil), "aws.kinesis.protobuf.Record")
	proto.RegisterType((*AggregatedRecord)(nil), "aws.kinesis.protobuf.AggregatedRecord")
	proto.RegisterType((*Message)(nil), "aws.kinesis.protobuf.Message")
	proto.RegisterType((*PutRecord)(nil), "aws.kinesis.protobuf.PutRecord")
	proto.RegisterType((*Flush)(nil), "aws.kinesis.protobuf.Flush")
	proto.RegisterType((*Attempt)(nil), "aws.kinesis.protobuf.Attempt")
	proto.RegisterType((*PutRecordResult)(nil), "aws.kinesis.protobuf.PutRecordResult")
	proto.RegisterType((*Credentials)(nil), "aws.kinesis.protobuf.Credentials")
	proto.RegisterType((*SetCredentials)(nil), "aws.kinesis.protobuf.SetCredentials")
	proto.RegisterType((*Dimension)(nil), "aws.kinesis.protobuf.Dimension")
	proto.RegisterType((*Stats)(nil), "aws.kinesis.protobuf.Stats")
	proto.RegisterType((*Metric)(nil), "aws.kinesis.protobuf.Metric")
	proto.RegisterType((*MetricsRequest)(nil), "aws.kinesis.protobuf.MetricsRequest")
	proto.RegisterType((*MetricsResponse)(nil), "aws.kinesis.protobuf.MetricsResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_0c7e4ef6cf0a996e) }

var fileDescriptor_messages_0c7e4ef6cf0a996e = []byte{
	// 981 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x55, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xaf, 0x9d, 0xa4, 0x89, 0x27, 0x6d, 0xda, 0x2e, 0x95, 0xf0, 0xdd, 0x71, 0xba, 0xe0, 0x03,
	0x5d, 0x84, 0x74, 0x91, 0x68, 0x05, 0x12, 0x2f, 0xc0, 0x5d, 0x11, 0x4a, 0x55, 0xdd, 0x81, 0xb6,
	0x15, 0x0f, 0xbc, 0x58, 0x5b, 0x7b, 0x9a, 0x58, 0x89, 0xed, 0xdc, 0xee, 0xfa, 0x68, 0xf9, 0x16,
	0x3c, 0xf2, 0x15, 0x78, 0x83, 0x2f, 0xc3, 0xd7, 0x41, 0x3b, 0xeb, 0x38, 0x76, 0x2e, 0x2d, 0x6f,
	0x3b, 0xb3, 0xf3, 0x9b, 0xfd, 0xcd, 0xdf, 0x85, 0x41, 0x8a, 0x4a, 0x89, 0x29, 0xaa, 0xf1, 0x52,
	0xe6, 0x3a, 0x67, 0xc7, 0xe2, 0x37, 0x35, 0x9e, 0x27, 0x19, 0xaa, 0xa4, 0x54, 0x5d, 0x17, 0x37,
	0x8f, 0xf7, 0xa2, 0x3c, 0xbb, 0x49, 0xa6, 0x56, 0x11, 0xbc, 0x84, 0xd6, 0x95, 0x98, 0xb2, 0x43,
	0x68, 0xcd, 0xf1, 0xce, 0x77, 0x86, 0xee, 0xc8, 0xe3, 0xe6, 0xc8, 0x8e, 0xa1, 0xf3, 0x5e, 0x2c,
	0x0a, 0xf4, 0xdd, 0xa1, 0x33, 0xf2, 0xb8, 0x15, 0x82, 0x7f, 0x1c, 0xd8, 0xe5, 0x18, 0xe5, 0x32,
	0x66, 0x63, 0xf8, 0x68, 0x29, 0xa4, 0x4e, 0x74, 0x92, 0x67, 0xe1, 0x1c, 0xef, 0xc2, 0x24, 0x8b,
	0xf1, 0x96, 0x5c, 0xb4, 0xf9, 0x51, 0x75, 0x75, 0x81, 0x77, 0xe7, 0xe6, 0x82, 0x7d, 0x05, 0x1f,
	0xe3, 0xed, 0x72, 0x91, 0x44, 0x89, 0x0e, 0x67, 0x42, 0xcd, 0x6a, 0x18, 0xf3, 0x44, 0x9b, 0x1f,
	0xaf, 0xae, 0x27, 0x42, 0xcd, 0x2a, 0x18, 0x83, 0x76, 0x2c, 0xb4, 0xf0, 0x5b, 0x43, 0x77, 0xb4,
	0xc7, 0xe9, 0xcc, 0x5e, 0x42, 0x5b, 0x8b, 0xa9, 0xf2, 0xdb, 0xc3, 0xd6, 0xa8, 0x7f, 0xf2, 0x68,
	0xbc, 0x2d, 0xce, 0xf1, 0x95, 0x98, 0x72, 0x32, 0x0b, 0xfe, 0x76, 0xe0, 0xf0, 0xd5, 0x74, 0x2a,
	0x71, 0x2a, 0x34, 0xc6, 0xf7, 0xd1, 0xd7, 0xe2, 0x7a, 0x81, 0xbe, 0x33, 0x6c, 0x8d, 0xbc, 0x26,
	0xfd, 0x2b, 0x73, 0xb1, 0x9d, 0xbe, 0xc5, 0xb8, 0x84, 0xd9, 0xa4, 0x6f, 0x61, 0x5f, 0x43, 0x57,
	0xd2, 0x83, 0xca, 0x6f, 0x11, 0xdb, 0x4f, 0xb6, 0xb3, 0xb5, 0xac, 0xf8, 0xca, 0x38, 0xf8, 0xb7,
	0x0d, 0xdd, 0x37, 0xb6, 0x9c, 0x6c, 0x00, 0x6e, 0x12, 0x97, 0x89, 0x75, 0x93, 0x98, 0x3d, 0x01,
	0x4f, 0xe5, 0x85, 0x8c, 0x30, 0x4c, 0xe2, 0x32, 0x77, 0x3d, 0xab, 0x38, 0x8f, 0xd9, 0xf7, 0x00,
	0xcb, 0x42, 0x87, 0xd6, 0x8f, 0xdf, 0x1a, 0x3a, 0xa3, 0xfe, 0xc9, 0xb3, 0xed, 0x6f, 0xfe, 0x5c,
	0x68, 0xfb, 0xec, 0x64, 0x87, 0x7b, 0xcb, 0x95, 0xc0, 0x4e, 0xa1, 0x73, 0xb3, 0x28, 0xd4, 0xcc,
	0x6f, 0x13, 0xf8, 0xc9, 0x76, 0xf0, 0x8f, 0xc6, 0x64, 0xb2, 0xc3, 0xad, 0x2d, 0xbb, 0x84, 0xa3,
	0xf5, 0xb3, 0xa1, 0x44, 0x55, 0x2c, 0xb4, 0xdf, 0x21, 0x07, 0x9f, 0xff, 0xcf, 0xeb, 0x9c, 0x8c,
	0x27, 0x3b, 0xfc, 0x60, 0xd9, 0x54, 0xb1, 0x0b, 0xd8, 0xb7, 0xcd, 0x5a, 0x48, 0x61, 0x8a, 0xe1,
	0xef, 0x92, 0xc3, 0xe7, 0xdb, 0x1d, 0x9e, 0xd5, 0x4d, 0x27, 0x3b, 0xbc, 0x89, 0x65, 0x3f, 0xc1,
	0x41, 0x8a, 0x5a, 0x26, 0x91, 0x0a, 0x25, 0xbe, 0x2b, 0x50, 0x69, 0xbf, 0x4b, 0xee, 0x3e, 0xdb,
	0xee, 0xee, 0x8d, 0x35, 0xe6, 0xd6, 0x76, 0xb2, 0xc3, 0x07, 0x69, 0x43, 0xc3, 0x38, 0x1c, 0xae,
	0x1d, 0xaa, 0x65, 0x9e, 0x29, 0xf4, 0x7b, 0x0f, 0x45, 0x5c, 0x79, 0xb4, 0xc6, 0x26, 0xe2, 0xb4,
	0xa9, 0x32, 0x24, 0x15, 0xea, 0x30, 0x92, 0x18, 0x63, 0xa6, 0x13, 0xb1, 0x50, 0xbe, 0xf7, 0x10,
	0xc9, 0x4b, 0xd4, 0x67, 0x6b, 0x5b, 0x43, 0x52, 0x35, 0x34, 0xaf, 0x0f, 0x61, 0x20, 0x22, 0x5d,
	0x88, 0x45, 0x58, 0x2e, 0x87, 0xe0, 0x0f, 0x07, 0xbc, 0x2a, 0xf7, 0xec, 0x19, 0xf4, 0x95, 0x96,
	0x28, 0xd2, 0x30, 0x13, 0x29, 0x96, 0x0b, 0x00, 0xac, 0xea, 0xad, 0x48, 0x91, 0x3d, 0x87, 0xfd,
	0xc6, 0x9c, 0xf8, 0x2e, 0x99, 0xec, 0xd5, 0x27, 0x84, 0x7d, 0x01, 0x47, 0x1f, 0x0c, 0x07, 0xf5,
	0x9e, 0xc7, 0x0f, 0x36, 0xc6, 0xa2, 0x1a, 0xe8, 0xf6, 0x7a, 0xa0, 0x83, 0x11, 0x74, 0xa8, 0x9f,
	0x3e, 0xa4, 0xe3, 0x34, 0xe9, 0x04, 0x7f, 0x3a, 0xd0, 0x7d, 0xa5, 0x35, 0xa6, 0x4b, 0x6d, 0x56,
	0x54, 0x8c, 0x0b, 0x61, 0xd7, 0xd6, 0x3e, 0xb7, 0x02, 0x7b, 0x0c, 0xbd, 0x78, 0xd5, 0x2f, 0x2e,
	0x5d, 0x54, 0x32, 0xf3, 0xa1, 0xab, 0x8a, 0x28, 0x42, 0xa5, 0x68, 0x9f, 0xf4, 0xf8, 0x4a, 0x64,
	0x4f, 0x01, 0x50, 0xca, 0x5c, 0x86, 0x51, 0x1e, 0x23, 0x75, 0xbe, 0xc7, 0x3d, 0xd2, 0x9c, 0xe5,
	0x31, 0x65, 0xc1, 0x5e, 0x97, 0x59, 0xa4, 0xd6, 0xf6, 0xf8, 0x1e, 0x29, 0xcb, 0x39, 0x0d, 0xfe,
	0x72, 0xe0, 0x60, 0xa3, 0xab, 0xd9, 0x37, 0xd0, 0x13, 0x96, 0xae, 0xa2, 0xdd, 0xd2, 0x3f, 0x79,
	0xba, 0xbd, 0x92, 0x65, 0x50, 0xbc, 0x32, 0xaf, 0x93, 0x75, 0x9b, 0x64, 0x1f, 0x41, 0x4f, 0xcd,
	0x84, 0x8c, 0xcd, 0xfc, 0xdb, 0x2c, 0x77, 0x49, 0x3e, 0x8f, 0xd9, 0x0b, 0xd3, 0x40, 0xef, 0x0a,
	0xcc, 0x22, 0x0c, 0xb3, 0x22, 0xbd, 0x46, 0x59, 0x06, 0x33, 0x58, 0xa9, 0xdf, 0x92, 0x36, 0xf8,
	0x05, 0xfa, 0xb5, 0x3e, 0x31, 0x55, 0x11, 0xf3, 0x72, 0xcb, 0x78, 0x9c, 0xce, 0x26, 0x27, 0x0a,
	0x23, 0x89, 0xba, 0x56, 0x77, 0xcf, 0x6a, 0x2e, 0xec, 0x0f, 0xa1, 0xf3, 0x39, 0x66, 0x25, 0x05,
	0x2b, 0x04, 0xef, 0x61, 0xd0, 0x6c, 0x4a, 0x53, 0xd3, 0x1b, 0xca, 0x1c, 0xb5, 0x3a, 0xd5, 0xb4,
	0xc7, 0xe1, 0xc6, 0xe4, 0x8d, 0x34, 0xec, 0x0c, 0xfa, 0xf5, 0x86, 0x37, 0x0f, 0xf5, 0x4f, 0x3e,
	0xbd, 0x67, 0xc8, 0xd7, 0x86, 0xbc, 0x8e, 0x0a, 0x4e, 0xc1, 0xfb, 0x21, 0x49, 0x31, 0x53, 0xa6,
	0xce, 0x0f, 0x7e, 0x67, 0xee, 0xfa, 0x3b, 0x9b, 0x42, 0xe7, 0x52, 0x0b, 0xad, 0xcc, 0x75, 0x94,
	0x17, 0x99, 0x26, 0x88, 0xc3, 0xad, 0x60, 0xdc, 0xa8, 0x22, 0x25, 0x88, 0xc3, 0xcd, 0xd1, 0xa4,
	0x29, 0x45, 0x91, 0x51, 0xf7, 0x38, 0x9c, 0xce, 0xc6, 0x2a, 0x4d, 0x32, 0xea, 0x67, 0x87, 0x9b,
	0x23, 0x69, 0xc4, 0xad, 0xdf, 0x29, 0x35, 0xe2, 0xd6, 0xb4, 0xc6, 0xae, 0x0d, 0xd7, 0xb8, 0xa8,
	0x8d, 0x1a, 0x9d, 0xd9, 0x77, 0x00, 0xf1, 0x8a, 0xbc, 0xa2, 0xff, 0xe4, 0xde, 0xa5, 0x5d, 0x05,
	0xc9, 0x6b, 0x10, 0xf6, 0x25, 0x74, 0x94, 0x09, 0x84, 0x88, 0xdd, 0xbb, 0xb3, 0x29, 0x56, 0x6e,
	0x2d, 0xa9, 0xbd, 0x30, 0xca, 0xb3, 0x58, 0x11, 0xf5, 0x36, 0x5f, 0x89, 0xc1, 0xb7, 0x30, 0x68,
	0x2e, 0xbf, 0x1a, 0x67, 0xa7, 0xe2, 0x5c, 0xc3, 0xdb, 0x3f, 0xa8, 0xc2, 0x9f, 0xc3, 0xc1, 0xc6,
	0xaa, 0x33, 0xdf, 0xe0, 0xba, 0xfe, 0x0f, 0x7c, 0x83, 0x16, 0xc7, 0x57, 0xc6, 0xaf, 0x4f, 0xe1,
	0x45, 0x94, 0xa7, 0x63, 0x91, 0x8a, 0xdf, 0xf3, 0x6c, 0x03, 0x11, 0x17, 0x11, 0xca, 0x0a, 0xfa,
	0x6b, 0x2f, 0xca, 0x33, 0x55, 0xa4, 0x28, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xc1, 0xf3,
	0x7b, 0x08, 0x09, 0x00, 0x00,
}
